# Generated by Django 3.2.4 on 2021-09-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
